name: Q4

on: [push]

permissions:
  contents: write

jobs:
  archiver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Générer Q4_archive_date.txt (JJ-MM-AAAA)
        run: |
          NAME="Thao Dujardin"
          D="$(date '+%d-%m-%Y')"
          F="Q4_archive_${D}.txt"
          {
            echo "Nom et prénom: $NAME"
            echo "===== Q4.java ====="
            cat Q4.java
          } > "$F"
          echo "FICHIER=$F" >> $GITHUB_ENV

      - name: Commit et push
        run: |
          git config user.email "thaodujardin@gmail.com"
          git config user.name "thaodujardin"
          git add "$FICHIER" || git add $(ls Q4_archive_*.txt | tail -n1)
          git commit -m "Q4: archiver Q4.java avec date1"
          git push
