name: Q5

on: [push]

permissions:
  contents: write

jobs:
  archiver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Générer Q5_archive_date.txt (JJ-MM-AAAA)
        run: |
          NAME="Thao Dujardin"
          D="$(date '+%d-%m-%Y')"
          F="Q5_archive_${D}.txt"
          {
            echo "Nom et prénom: $NAME"
            echo "===== Q5.java ====="
            cat Q5.java
          } > "$F"
          echo "FICHIER=$F" >> $GITHUB_ENV

      - name: Commit et push
        run: |
          git config user.email "thaodujardin@gmail.com"
          git config user.name "thaodujardin"
          git add "$FICHIER" || git add $(ls Q5_archive_*.txt | tail -n1)
          git commit -m "Q5: archiver Q5.java avec date"
          git push
